#ifndef PLATFORMER_CONSTANTS_H
#define PLATFORMER_CONSTANTS_H

#define G 2000
#define PLAYER_TERMINAL_VELOCITY 700.0f
#define PLAYER_MAX_JUMP_HEIGHT 200.0f
#define PLAYER_JUMP_SPD 350.0f
#define PLAYER_HOR_SPD 200.0f

#endif //PLATFORMER_CONSTANTS_H